# tmux configuration

set -g default-terminal "screen-256color"           # make sure the terminal colors are correct

set -g prefix C-a                                   # Set the prefix for tmux to ctrl + A (makes it easier on the Voyager keyboard)
unbind C-b
bind-key C-a send-prefix

unbind %                                            # Bind split horizontal to |
bind | split-window -h

unbind '"'                                          # Bind split horizontal to -
bind - split-window -v 

unbind r                                            # Reload the tmux.conf file with 'r'
bind r source-file ~/.tmux.conf                     # todo: will need to change this for windows
# bind r source-file $HOME/.tmux.conf

bind -r j resize-pane -D 5                          # Resizes the pane 5 units down
bind -r k resize-pane -U 5                          # Resizes the pane 5 units up
bind -r h resize-pane -L 5                          # Resizes the pane 5 units to the left 
bind -r l resize-pane -R 5                          # Resizes the pane 5 units to the right
bind -r m resize-pane -Z                            # Maximizes the tmux pane

set -g status-position top                          # Moves the status bar to the top.

set -g mouse on                                     # Allows mouse to resize window. (Doesn't work for me?)

set -g @plugin 'tmux-plugins/tpm'                   # Use TPM as the plugin manager

set-window-option -g mode-keys vi                   # Allows vim motions when scrolling through tmux window text copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection# Allows visual mode to make selections
bind-key -T copy-mode-vi 'y' send -X copy-selection # Allows y key to copy selections like in vim
unbind -T copy-mode-vi MouseDragEnd1Pane            # Allows dragging with mouse easier (don't worry about it for now)


#  ---- Plugins ----
set -g @plugin 'christoomey/vim-tmux-navigator'     # Allows moving panes using hjkl
set -g @plugin 'dracula/tmux'                       # Theme options for status bar (Dracula)
set -g @dracula-plugins "battery network time"
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session


run '~/.tmux/plugins/tpm/tpm'                       # Initialize tmux plugin manager, keep this at the bottom.
