import = [
  "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"

opacity = 0.8

[font]
normal.family = "FiraCode Nerd Font"
size = 18
